seq_len: 36
pred_len: 3
hidden_dim: 24
kernel_size: 5
dilation_pattern:
- 1
- 2
- 4
dilated_blocks: 3
sinusoidal_dim: 24
ema_decay: 0.8
learnable_ema: false
se_block: none
residual: all_blocks
dropout: 0.2
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: false
