seq_len: 30
pred_len: 4
hidden_dim: 40
kernel_size: 3
dilation_pattern:
- 2
- 4
dilated_blocks: 2
sinusoidal_dim: 16
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_4
residual: last_block
dropout: 0.0
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: false
