seq_len: 18
pred_len: 3
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 1
- 3
- 9
dilated_blocks: 3
sinusoidal_dim: 4
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_8
residual: all_blocks
dropout: 0.0
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: true
