seq_len: 24
pred_len: 4
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 1
- 2
- 4
- 8
dilated_blocks: 4
sinusoidal_dim: 24
ema_decay: 0.8
learnable_ema: true
se_block: squeeze_ratio_8
residual: 'off'
dropout: 0.1
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: true
