seq_len: 30
pred_len: 6
hidden_dim: 40
kernel_size: 3
dilation_pattern:
- 1
- 2
- 4
dilated_blocks: 3
sinusoidal_dim: 8
ema_decay: 0.8
learnable_ema: false
se_block: squeeze_ratio_4
residual: last_block
dropout: 0.15
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: false
