seq_len: 48
pred_len: 6
hidden_dim: 24
kernel_size: 5
dilation_pattern:
- 1
- 2
dilated_blocks: 2
sinusoidal_dim: 16
ema_decay: 0.8
learnable_ema: true
se_block: none
residual: 'off'
dropout: 0.05
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: true
