seq_len: 30
pred_len: 3
hidden_dim: 32
kernel_size: 5
dilated_blocks: 2
dilation_pattern:
- 1
- 2
sinusoidal_dim: 4
ema_decay: 0.8
learnable_ema: true
se_block: squeeze_ratio_8
residual: 'off'
dropout: 0.05
target_weights:
- 0.6
- 1.0
- 1.4
normalized_mae: false
