seq_len: 24
pred_len: 6
hidden_dim: 32
kernel_size: 5
dilation_pattern:
- 2
- 4
- 8
- 16
dilated_blocks: 4
sinusoidal_dim: 4
ema_decay: 0.8
learnable_ema: false
se_block: none
residual: 'off'
dropout: 0.0
target_weights:
- 0.6
- 1.0
- 1.4
normalized_mae: false
