seq_len: 30
pred_len: 3
hidden_dim: 24
kernel_size: 5
dilation_pattern:
- 2
- 4
dilated_blocks: 2
sinusoidal_dim: 4
ema_decay: 0.95
learnable_ema: false
se_block: squeeze_ratio_8
residual: all_blocks
dropout: 0.1
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: false
