seq_len: 18
pred_len: 4
hidden_dim: 40
kernel_size: 3
dilation_pattern:
- 1
- 2
dilated_blocks: 2
sinusoidal_dim: 4
ema_decay: 0.8
learnable_ema: false
se_block: none
residual: 'off'
dropout: 0.15
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: false
