seq_len: 18
pred_len: 6
hidden_dim: 40
kernel_size: 5
dilation_pattern:
- 2
- 4
dilated_blocks: 2
sinusoidal_dim: 8
ema_decay: 0.95
learnable_ema: false
se_block: none
residual: 'off'
dropout: 0.05
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: false
