seq_len: 30
pred_len: 6
hidden_dim: 24
kernel_size: 5
dilated_blocks: 3
dilation_pattern:
- 1
- 3
- 9
sinusoidal_dim: 8
ema_decay: 0.8
learnable_ema: true
se_block: squeeze_ratio_8
residual: 'off'
dropout: 0.0
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: false
