seq_len: 48
pred_len: 3
hidden_dim: 32
kernel_size: 5
dilated_blocks: 2
dilation_pattern:
- 1
- 2
sinusoidal_dim: 24
ema_decay: 0.9
learnable_ema: false
se_block: none
residual: 'off'
dropout: 0.1
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: true
