seq_len: 18
pred_len: 4
hidden_dim: 48
kernel_size: 5
dilation_pattern:
- 2
- 4
dilated_blocks: 2
sinusoidal_dim: 4
ema_decay: 0.8
learnable_ema: true
se_block: none
residual: 'off'
dropout: 0.15
target_weights:
- 1.0
- 1.4
- 0.8
normalized_mae: true
