seq_len: 24
pred_len: 4
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 1
- 2
dilated_blocks: 2
sinusoidal_dim: 4
ema_decay: 0.9
learnable_ema: true
se_block: squeeze_ratio_8
residual: 'off'
dropout: 0.1
target_weights:
- 0.6
- 1.0
- 1.4
normalized_mae: true
