seq_len: 18
pred_len: 6
hidden_dim: 24
kernel_size: 5
dilation_pattern:
- 1
- 2
- 4
- 8
dilated_blocks: 4
sinusoidal_dim: 24
ema_decay: 0.8
learnable_ema: true
se_block: squeeze_ratio_4
residual: all_blocks
dropout: 0.0
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: true
