seq_len: 24
pred_len: 3
hidden_dim: 24
kernel_size: 5
dilated_blocks: 4
dilation_pattern:
- 1
- 2
- 4
- 8
sinusoidal_dim: 4
ema_decay: 0.9
learnable_ema: false
se_block: none
residual: all_blocks
dropout: 0.2
target_weights:
- 0.6
- 1.0
- 1.4
normalized_mae: true
