seq_len: 48
pred_len: 4
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 2
- 4
dilated_blocks: 2
sinusoidal_dim: 4
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_8
residual: 'off'
dropout: 0.2
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: true
