seq_len: 36
pred_len: 3
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 2
- 4
- 8
dilated_blocks: 3
sinusoidal_dim: 8
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_4
residual: last_block
dropout: 0.0
target_weights:
- 0.6
- 1.0
- 1.4
normalized_mae: false
