seq_len: 24
pred_len: 3
hidden_dim: 40
kernel_size: 5
dilated_blocks: 2
dilation_pattern:
- 1
- 2
sinusoidal_dim: 24
ema_decay: 0.8
learnable_ema: true
se_block: squeeze_ratio_8
residual: all_blocks
dropout: 0.15
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: false
