seq_len: 24
pred_len: 4
hidden_dim: 32
kernel_size: 5
dilation_pattern:
- 2
- 4
- 8
- 16
dilated_blocks: 4
sinusoidal_dim: 8
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_4
residual: 'off'
dropout: 0.05
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: false
