seq_len: 18
pred_len: 3
hidden_dim: 32
kernel_size: 3
dilation_pattern:
- 2
- 4
- 8
dilated_blocks: 3
sinusoidal_dim: 16
ema_decay: 0.8
learnable_ema: false
se_block: squeeze_ratio_4
residual: all_blocks
dropout: 0.0
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: false
