seq_len: 30
pred_len: 6
hidden_dim: 32
kernel_size: 5
dilation_pattern:
- 2
- 4
- 8
- 16
dilated_blocks: 4
sinusoidal_dim: 4
ema_decay: 0.95
learnable_ema: true
se_block: none
residual: all_blocks
dropout: 0.1
target_weights:
- 1.3
- 1.0
- 0.7
normalized_mae: true
