seq_len: 24
pred_len: 6
hidden_dim: 24
kernel_size: 5
dilation_pattern:
- 2
- 4
- 8
- 16
dilated_blocks: 4
sinusoidal_dim: 8
ema_decay: 0.8
learnable_ema: true
se_block: none
residual: 'off'
dropout: 0.2
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: true
