seq_len: 18
pred_len: 3
hidden_dim: 40
kernel_size: 3
dilation_pattern:
- 1
- 2
- 4
- 8
dilated_blocks: 4
sinusoidal_dim: 8
ema_decay: 0.8
learnable_ema: false
se_block: squeeze_ratio_4
residual: 'off'
dropout: 0.2
target_weights:
- 1.0
- 1.0
- 1.0
normalized_mae: true
