seq_len: 18
pred_len: 3
hidden_dim: 24
kernel_size: 3
dilation_pattern:
- 1
- 3
- 9
dilated_blocks: 3
sinusoidal_dim: 8
ema_decay: 0.9
learnable_ema: false
se_block: squeeze_ratio_4
residual: all_blocks
dropout: 0.2
target_weights:
- 0.8
- 1.2
- 1.0
normalized_mae: false
